[package]
name = "scale_colorizr"
version = "0.1.0"
edition = "2021"
authors = ["METALWINGS DSP <hello@murl.digital>"]
license = "GPL-3.0-or-later"
homepage = "https://crouton.net"
description = "Filter based sound colorizer"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
crossbeam = "0.8.4"
colorgrad = { git = "https://github.com/mazznoer/colorgrad-rs.git" }
cozy-util = { git = "https://github.com/cozy-dsp/cozy-util.git" }
lazy_static = "1.4.0"
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs", "simd"] }
nih_plug_egui = { git = "https://github.com/robbert-vdh/nih-plug.git" }
noise = "0.8.2"
num-complex = "0.4.5"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
